language: groovy
jdk:
- oraclejdk7
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Jason Heithoff"
  - GIT_EMAIL="ci@grails-seed.org"
before_script:
- rm -rf target
- chmod +x ./travis-build.sh
script: ./travis-build.sh
